services:
  - type: web
    name: blog-server
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npx ts-node src/index.ts
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
